ARG PHP_VERSION
FROM php:${PHP_VERSION}

LABEL maintainer="Aron Peyroteo <aron@mqx.com.br>" \
  org.label-schema.name="aronpc/php" \
  org.label-schema.description="Docker images for PHP" \
  org.label-schema.build-date=$BUILD_DATE \
  org.label-schema.schema-version="1.0" \
  org.label-schema.vcs-url="https://github.com/aronpc/php"

RUN apt update -yqqq
RUN apt install -yqqq unzip git

ADD https://github.com/mlocati/docker-php-extension-installer/releases/latest/download/install-php-extensions /usr/local/bin/

RUN chmod +x /usr/local/bin/install-php-extensions

RUN install-php-extensions amqp > /dev/null 2>&1
RUN install-php-extensions apcu > /dev/null 2>&1
RUN install-php-extensions ast > /dev/null 2>&1
RUN install-php-extensions bcmath > /dev/null 2>&1
RUN install-php-extensions bz2 > /dev/null 2>&1
RUN install-php-extensions calendar > /dev/null 2>&1
RUN install-php-extensions dba > /dev/null 2>&1
RUN install-php-extensions decimal > /dev/null 2>&1
RUN install-php-extensions enchant > /dev/null 2>&1
RUN install-php-extensions ev > /dev/null 2>&1
RUN install-php-extensions event > /dev/null 2>&1
RUN install-php-extensions exif > /dev/null 2>&1
RUN install-php-extensions gd > /dev/null 2>&1
RUN install-php-extensions gettext > /dev/null 2>&1
RUN install-php-extensions gmagick > /dev/null 2>&1
RUN install-php-extensions gmp > /dev/null 2>&1
RUN install-php-extensions gnupg > /dev/null 2>&1
RUN install-php-extensions grpc > /dev/null 2>&1
RUN install-php-extensions http > /dev/null 2>&1
RUN install-php-extensions igbinary > /dev/null 2>&1
RUN install-php-extensions imap > /dev/null 2>&1
RUN install-php-extensions inotify > /dev/null 2>&1
RUN install-php-extensions intl > /dev/null 2>&1
RUN install-php-extensions json_post > /dev/null 2>&1
RUN install-php-extensions ldap > /dev/null 2>&1
RUN install-php-extensions lzf > /dev/null 2>&1
RUN install-php-extensions mcrypt > /dev/null 2>&1
RUN install-php-extensions memcache > /dev/null 2>&1
RUN install-php-extensions memcached > /dev/null 2>&1
RUN install-php-extensions mongodb > /dev/null 2>&1
RUN install-php-extensions msgpack > /dev/null 2>&1
RUN install-php-extensions oauth > /dev/null 2>&1
RUN install-php-extensions oci8 > /dev/null 2>&1
RUN install-php-extensions odbc > /dev/null 2>&1
RUN install-php-extensions opcache > /dev/null 2>&1
RUN install-php-extensions pcntl > /dev/null 2>&1
RUN install-php-extensions pdo_firebird > /dev/null 2>&1
RUN install-php-extensions pdo_mysql > /dev/null 2>&1
RUN install-php-extensions pdo_oci > /dev/null 2>&1
RUN install-php-extensions pdo_pgsql > /dev/null 2>&1
RUN install-php-extensions pgsql > /dev/null 2>&1
RUN install-php-extensions redis > /dev/null 2>&1
RUN install-php-extensions smbclient > /dev/null 2>&1
RUN install-php-extensions snmp > /dev/null 2>&1
RUN install-php-extensions soap > /dev/null 2>&1
RUN install-php-extensions sockets > /dev/null 2>&1
RUN install-php-extensions ssh2 > /dev/null 2>&1
RUN install-php-extensions timezonedb > /dev/null 2>&1
RUN install-php-extensions uuid > /dev/null 2>&1
RUN install-php-extensions xdebug > /dev/null 2>&1
RUN install-php-extensions xhprof > /dev/null 2>&1
RUN install-php-extensions xmldiff > /dev/null 2>&1
RUN install-php-extensions xsl > /dev/null 2>&1
RUN install-php-extensions zip > /dev/null 2>&1

# Set correct environment variables
ENV HOME=/home/abc
ENV COMPOSER_HOME=$HOME/.composer

# Install composer
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
COPY --from=composer:1 /usr/bin/composer /usr/bin/composer1

USER root

WORKDIR /tmp

RUN adduser --disabled-password --gecos "" abc 
RUN echo "abc  ALL = ( ALL ) NOPASSWD: ALL" >> /etc/sudoers
RUN mkdir -p /var/www/html
RUN rm -rf ${COMPOSER_HOME}/cache/*
RUN chown -R abc:abc /var/www $HOME

ADD ./fpm/fpm-pool.conf /usr/local/etc/php-fpm.d/www.conf
ADD ./fpm/php.ini /usr/local/etc/php/php.ini

ENV PATH "$PATH:$COMPOSER_HOME/vendor/bin"

#RUN apk del --purge grep build-base file openssl-dev

RUN rm -rf /tmp/* \
  /usr/includes/* \
  /usr/share/man/* \
  /usr/src/* \
  /var/cache/apk/* \
  /var/tmp/* \
  /opt/oracle/instantclient* \
  /var/lib/apt/lists/*

VOLUME ${HOME}

USER abc

WORKDIR /var/www/html

EXPOSE 9000 9001