name: Make images

env:
    REPOSITORY_NAME: 'aronpc/php'
    LATEST_VERSION: '8.2'
    PHP_VERSIONS: '7.0 7.1 7.2 7.4 8.0 8.1 8.2'

on:
  push:
    branches:
      - master
  schedule: # execute every monday
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build and push images'
    steps:
      - name: "DockerHub login"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Branch checkout"
        uses: actions/checkout@v3
      - name: "Build and push images"
        run: bash ./make.sh