name: Make images

on:
  schedule:
    - cron: "0 0 * * 1"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: 'Build and push images'
    strategy:
      matrix:
        version: [7.2 7.4 8.0 8.1]
    steps:
      - name: "DockerHub login"
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: "Branch checkout"
        uses: actions/checkout@v3
      - name: "Build and Push Docker Images"
        env:
          PHP_VERSIONS: ${{ matrix.version }}
          LATEST_VERSION: ${{ vars.LATEST_VERSION }}
          REPOSITORY_NAME: ${{ vars.REPOSITORY_NAME }}
        run: |
          make all
